### ISSUE TITLE
Redesign: About Page

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#299]
Create the About page

![image](https://user-images.githubusercontent.com/16775804/28209117-03842e2e-6889-11e7-89fe-d73f5d3168ff.png)
![image](https://user-images.githubusercontent.com/16775804/28209124-0e037f4e-6889-11e7-9cb0-afc599fda0ba.png)
![image](https://user-images.githubusercontent.com/16775804/28209132-13d0bf5e-6889-11e7-8ed1-1b8f1cc26fd0.png)

- [x] Top 'Driven by Our Values' section with logo and shadow bottom
- [x] dwyl definition section
- [x] Grey 'More Than Just Software' title, subtitle
- [x] Community and Team buttons
- [x] People
- [x] Transparency
- [x] The Planet
- [x] Organic growth

**Comment by markwilliamfirth** [comment]
Capitalisation needs updating according to https://github.com/dwyl/dwyl-site/issues/234#issuecomment-308735303

e.g. our -> Our

dwyl pronunciation should be dwɪɫ

Links are yellow and underlined - these are different to links on the blog page - we should probably have a convention for links at some point

Otherwise great - happy for us to go ahead and we can continue to iterate on it later 👍
