### ISSUE TITLE
Create Time App Beta Tester Google Form

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#309]
**As a** user on the app page
**I want to** be able to enter my details into a functioning form
**So that** I can receive updates to become a beta tester.

Page exists but not currently set up with functioning form.
Need to personalise the thanks message with user's name from the form details.

**Comment by iteles** [comment]
@Cleop I used this for our wedding website (MVP): https://github.com/dwyl/html-form-send-email-via-google-script-without-server

**Comment by iteles** [comment]
@Cleop If you use the above, please note that you need to read _each step **very carefully**_ as there are a few 'gotchas' if the steps aren't followed precisely.

But when I did it for the wedding website, took me less than 2 hours (closer to 1.5) to implement and since then @mckennapsean has added some additional troubleshooting to the docs - they're in fantastic shape!

**Comment by Cleop** [comment]
Who should emails be sent to? Mark? Info? something else?

**Comment by markwilliamfirth** [comment]
@Cleop what spreadsheet does this go to?

**Comment by markwilliamfirth** [comment]
https://docs.google.com/spreadsheets/d/1PfPRD54M6K2hiN-1IkTC7IkJVRMAuEGoX1qz2cK5HrQ/edit?ts=59d204cc#gid=0

@Cleop thanks for sending over email - could you please transfer sheet ownership rights to me?

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/dwyl-site/issues/417
