### ISSUE TITLE
Update Nelson's and Conor's Bio

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#322]
Relates to #288 
Some bios on the team page are very long and not fitting with the UI:
![image](https://user-images.githubusercontent.com/16775804/30474106-72c4c5f8-99fa-11e7-9dd6-ca1051f46291.png)
Either we need to impose an approximate word limit and ask people to revise their bios accordingly or we need to change the UI to allow for longer bios.

**Comment by markwilliamfirth** [comment]
@Cleop yes there is a word limit - this one needs to be shortened - I can do this

**Comment by Cleop** [comment]
I think it's worth checking all for more that have broken the word limit, at a glance @Conorc1000 's is over 100 words.

**Comment by markwilliamfirth** [comment]
Nelson's should be replaced by:

Hi! I'm Nelson and I'm on a quest to change the world with technology!
I systematically catalog & share everything I learn so that 
anyone can learn what I know fast and for FREE: https://github.com/dwyl?q=learn

My job is to write & review code, help others learn & grow and "unblock" things.

Interests: Any Technology or Idea that improves the lives of of people, animals and the environment.
e.g: "agritech" to improve food supply and eliminate hunger & malnutrition in the world, 
"medtech" to help people get/stay healthy and "edtech" to help everyone learn anything!


Conor:

Hi 👋 my name is Conor. My favourite part of working here is [dwyl summer](https://github.com/dwyl/summer/blob/master/README.md#what); its at great chance to get to know the rest of the team better and catch some rays 🌞. I enjoy the relaxed culture - it makes easy to get along with everyone, and the fact we get to play pivotal roles in projects from an early stage. The freedom to work remotely has opened up so many great opportunities for me to travel more (Scotland, Spain, France, Mexico, [Colombia](https://twitter.com/carlisle_jack/status/857629227579035649)). Outside of DWYL I am a keen boxer and motorcyclist 🏍.
