### ISSUE TITLE
Differentiate job titles and names / liven up team page

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#363]
Or something else to liven up the page a bit and differentiate names and titles

<img width="502" alt="screen shot 2017-09-22 at 14 51 14" src="https://user-images.githubusercontent.com/5732209/30747578-9cd6dab0-9fa5-11e7-943c-25c4cde63232.png">

**Comment by finnhodgkin** [comment]
I'll make a PR so we can see what it looks like :+1:

**Comment by iteles** [comment]
@markwilliamfirth I think you're right in that it needs a little liveliness.

I got to this party late but in light of your comment here: https://github.com/dwyl/dwyl-site/pull/366#issuecomment-331965053 I'm not too keen on the job titles being enhanced as that's not really something we value - I'd be much more keen on highlighting people's names in this case.

We might need a little input from our more design-sensitive dwylers here. Can we get a screenshot of more of the page please so that we have more of a basis for people to contribute without having to go digging?

**Comment by finnhodgkin** [comment]
![dwyl - google chrome_042](https://user-images.githubusercontent.com/22300773/30832185-1ba40acc-a242-11e7-8a36-bbc989898c7d.png)

Or with more focus on the names:
![dwyl - google chrome_043](https://user-images.githubusercontent.com/22300773/30832429-fa12aad4-a242-11e7-892e-a2aa7772fc0c.png)

**Comment by ZooeyMiller** [comment]
Another thing to note is that when run through pa11y (accessibility checker) it errors on dwyl teal on a white background due to insufficient contrast.

**Comment by iteles** [comment]
Loving the focus on the names @finnhodgkin, feels very 'us' ;)

**Comment by finnhodgkin** [comment]
What do you think @markwilliamfirth ?

I'm happy to make the change :+1:

The other minor change I was thinking about making to the team page is to enlarge the photo and lower the padding when only one profile is shown:

![selection_048](https://user-images.githubusercontent.com/22300773/30857421-8ea430d0-a2b3-11e7-81da-5c2395f09035.png)

**Comment by markwilliamfirth** [comment]
@finnhodgkin go for it!

**Comment by markwilliamfirth** [comment]
completed
