### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#395]
- [ ] General info about site (What it's for, why we have it, etc)
- [x] Who made it and who's responsible for what (e.g. Harry for design - link for invision, asset location)
- [x] Technologies used + how js should be used
- [x] How the submission and sign-up forms work
- [ ] Conventions (e.g. branding, capitalisation and links)
- [ ] How and why it's hosted
- [x] How to clone repo, set up live server and view locally
- [x] How to add yourself as a new team member
- [ ] How to add a blog post

(Feel free to expand on and/or reorder these points as you see fit)

**Comment by finnhodgkin** [comment]
By 'link for invision and assets', do you mean a publicly accessibly link to the invision designs and assets, because I'm not sure that's possible. I might be wrong though, I've hardly used Invision :confused:.

I could save out the designs and host them somewhere if we want them publicly available.

**Comment by markwilliamfirth** [comment]
@finnhodgkin I just mean a link to the designs - I presume if someone doesn't have access it will come up with a splash that says 'you don't have access, please request' so it will then email those who do, which is good enough (maybe?)

**Comment by finnhodgkin** [comment]
Found a public share link: https://projects.invisionapp.com/share/VSBOA5D8B

**Comment by ZooeyMiller** [comment]
I'm hesitant to add the information of how to run the site locally with live-server, because strictly speaking it doesn't work. Unless we were happy to change all links on the site to include `.html` on the end, it just won't work on live-server.

**Comment by ZooeyMiller** [comment]
I'm happy to add information on how it's hosted, but unclear on "why it's hosted" in this way?

**Comment by markwilliamfirth** [comment]
@ZooeyMiller in response to https://github.com/dwyl/dwyl-site/issues/395#issuecomment-334413946

Do we have a better solution for viewing the site other than live-server + adding .html in the view or permanently changing all the links to .html in the code?

in response to https://github.com/dwyl/dwyl-site/issues/395#issuecomment-334414429
We just need a line explaining why - as in it's currently hosted on GitHub Pages as an interim solution as the plan is for the site to use a phpenix server, which has yet to be built. We've used GitHub pages because it integrates with GitHub well and it's free. The cons of GitHub pages are that it doesn't allow https with custom domains, so we have used a workaround...etc

**Comment by ZooeyMiller** [comment]
@iteles asked that we ask you to do the remaining updates to the readme, just so we don't duplicate work by us asking you questions, you commenting answers, then us putting them in the README. 

In terms of the running locally, there are no better solutions that I immediately know of.

**Comment by nelsonic** [comment]
Agree that we will need to update the `README.md` when the **`new`** site https://github.com/dwyl/dwyl-site/issues/493 is launched.
